name: CI/CD frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front/**'
      - '.github/workflows/ci-cd-frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'front/**'
    - '.github/workflows/ci-cd-frontend.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: clone the source code for the backend
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      # ✅ clé anti-bug rollup/npm: lockfile Linux
      - name: Recreate Linux-specific lockfile
        working-directory: front
        run: |
          rm -f package-lock.json
          npm install --package-lock-only --ignore-scripts
      - name: Install & build Angular
        run: |
          cd front          
          npm ci
          npm run build
          npm run test:ci
        # publish code coverage to GITHUB with artifact
      - name: Upload code coverage to GitHub - Frontend
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-front
          path: front/coverage/ycywapp/

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=aflouat_ywyc-poc-front
            -Dsonar.organization=aflouat
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.exclusions=node_modules/**,dist/**
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=front/coverage/ycywapp/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build front Docker image
        run: |
            docker build -t aflouat/ycywapp-front:latest -f front/Dockerfile front

      - name: Push Docker image to Docker Hub
        run: |
          docker tag aflouat/ycywapp-front:latest aflouat/ycywapp-front:${{ github.sha }}
          docker push aflouat/ycywapp-front:${{ github.sha }}
          docker push aflouat/ycywapp-front:latest

