name: CI/CD backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'back/**'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:


      - name: clone the source code for the backend
        uses: actions/checkout@v4
        # Backend build & test
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '22'
      - name: Build & test Spring Boot
        run: |
          cd back
          ./mvnw clean verify
            - name: Prepare mvnw
        run: |
          chmod +x back/mvnw || true
      # publish code coverage to GITHUB with artifact
      - name: Upload code coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
            name: code-coverage-back
            path: back/target/site/jacoco/


      - name: SonarQube Scan - Backend
        run: |
          cd back
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t aflouat/ycywapp-back:latest -f back/Dockerfile back


      - name: Push Docker image to Docker Hub
        run: |
          docker tag aflouat/ycywapp-back:latest aflouat/ycywapp-back:${{ github.sha }}
          docker push aflouat/ycywapp-back:${{ github.sha }}
          docker push aflouat/ycywapp-back:latest
